### ISSUE TITLE
Repo information absent in package.json

### ISSUE THREAD

**Issue by rajasegar-c** [wagenet/ember-error-codemod#1]
Hi @wagenet , thanks a lot for this codemod, just wanted to inform you that
We need to add the repo info in package.json for discoverability reasons
```json
{
...
 "repository": {
    "type": "git",
    "url": "git+https://github.com/wagenet/ember-error-codemod.git"
  },
...
}
```

**Comment by wagenet** [comment]
Thanks! Can you send a PR for this?
